### ISSUE TITLE
Añadir soporte para las escenas en un grupo de escenas

### ISSUE THREAD

**Issue by 1p61** [qhariN/himnario-adventista-obs#4]
Que tal brother. Bendiciones.
Me encanto tu aportación a OBS con el Himnario Adventista, sin embargo tengo un problema. 
Lo que sucede es que para mis transmisiones a YT normalmente uso una cámara abajo de los himnos. Sucede que al agrupar las fuentes el plugin no las reconoce y solo las corre de manera individual dentro de Fuentes.
De mi parte me encanta tu aportación.
Que Dios siga bendiciendo tu ministerio digital
ATTE
Eduardo Espinosa
Dir. de Marketing y Redes Sociales de la IASD Maria Henriquez-Panamá.

**Comment by jhormanrus** [comment]
> Que tal brother. Bendiciones. Me encanto tu aportación a OBS con el Himnario Adventista, sin embargo tengo un problema. Lo que sucede es que para mis transmisiones a YT normalmente uso una cámara abajo de los himnos. Sucede que al agrupar las fuentes el plugin no las reconoce y solo las corre de manera individual dentro de Fuentes. De mi parte me encanta tu aportación. Que Dios siga bendiciendo tu ministerio digital ATTE Eduardo Espinosa Dir. de Marketing y Redes Sociales de la IASD Maria Henriquez-Panamá.

Querido hermano, la aplicación ahora soporta la agrupación de las escenas, gracias por su recomendación.

Aparte del tema, me gustaría conocer su experiencia al implementar esta herramienta contestando las siguientes preguntas:

1. ¿fue difícil entender la documentación?
2. ¿tuvo dudas acerca de alguna funcionalidad ó la configuración?
3. ¿cree que falta abordar algún detalle en la documentación?
4. ¿preferiría que la aplicación esté en español?

Estaré muy agradecido por su respuesta. Espero que esta herramienta le pueda ser muy util y que pueda darlo a conocer a más personas.
