### ISSUE TITLE
¿Existe algún API del Himnario?

### ISSUE THREAD

**Issue by Ignaciomanchu1998** [qhariN/himnario-adventista-obs#5]
Muy buenas días, tardes o noches.

Una consulta, ¿existe algún api que pueda usar?

Saludos.

**Comment by jh0rman** [comment]
Hola.
Si te refieres a una API relacionada al himnario puedes usar el [HImnario Adventista API](https://github.com/jhormanrus/himnario-adventista-api). Todos los datos del himnario están almacenados en una base de datos SQLite [aquí](https://github.com/jhormanrus/himnario-adventista-api/tree/master/src/database).
